### ISSUE TITLE
Release 1.4 tracking issue

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#288]
basedmypy 1.4 will be based, and based on mypy 0.961 and will include new features:
- [x] `ignore_any_from_errors` (#281)
- [x] render types better (#290)
- [x] `infer_function_types` (#75)
- [x] `Untyped` type (#299)
- [x] infer property types (#305)

Along with some minor other fixes:
- show basedmypy info when a crash appears
- [x] Depend on basedtyping (#311)

TODO:
- [x] Update the wiki for the new features.
- [x] KotlinIsland/basedtyping/pull/44
- [x] GitHub release

timeline:
- RC ASAP including #320, #322, #323
- Stable on 13/7

Bugs:
- minor #320
- minor #322
- minor #323 
- normal #346
